var stack = [1, 2, 3, 4];
var top = 0;
top = stack.lrngth - 1;
var num = prompt("Enter a number");
stack.push(num);
top = top + 1;
console.log("value of top: " + top);
console.log("top most element is: " + stack);
var deleted = stack.pop();
top = top - 1;
console.log("Stack after pop: " + stack);
